### ISSUE TITLE
[flaky test] TestGRPCStatusCode: parent-scoped context expires while its parallel subtests wait for a slot

### ISSUE THREAD

**Issue by liran-funaro** [hyperledger/fabric-x-committer#763]
`TestGRPCStatusCode` and **all five** of its subtests failed in CI on #759, in the same run as
the three snapshot-clone failures tracked in #762:

- failed: https://github.com/hyperledger/fabric-x-committer/actions/runs/31577421711/job/94052612596?pr=759
- unrelated to #759, which touches no `service/vc` code.

```
=== FAIL: service/vc TestGRPCStatusCode (47.39s)

--- FAIL: TestGRPCStatusCode/GetTransactionsStatus_returns_an_invalid_argument_error (0.00s)
    validator_committer_service_test.go:551: Error: Should be true
--- FAIL: TestGRPCStatusCode/SetLastCommittedBlockNumber_returns_an_internal_error (0.00s)
--- FAIL: TestGRPCStatusCode/GetNextBlockNumberToCommit_returns_an_internal_error (0.00s)
--- FAIL: TestGRPCStatusCode/GetPolicies_returns_an_internal_error (0.00s)
--- FAIL: TestGRPCStatusCode/GetTransactionsStatus_returns_an_internal_error (0.00s)
```

The fingerprint looks self-contradictory: the parent ran 47.39 s, every subtest took 0.00 s, and
the failures include the subtest expecting `InvalidArgument` from a `nil` request — pure
server-side validation that never touches the database. The four `Internal` subtests should also
have taken ~3 s each (the retry budget the test installs), not 0.00 s.

### Cause

`createContext(t)` (`validator_committer_service_test.go:764`) creates a 5-minute deadline in the
**parent body**, and all five `t.Parallel()` subtests share it. Parallel subtests are released
only after the parent body returns, and then wait for a `-parallel` slot — GOMAXPROCS, i.e. 4 on
`ubuntu-latest`. In this run three snapshot tests were each holding a slot for 300 s (#762), so
the subtests sat queued past the deadline they had inherited; when they finally ran, every RPC
returned immediately with the context error, which is neither `InvalidArgument` nor `Internal`.

The CI timeline matches: the subtest failures appear right after the 08:24:37 log lines, which is
the moment the first stuck snapshot test hit its 300 s deadline and released its slot.

Two details of Go's `testing` explain the durations (verified against Go 1.26
`src/testing/testing.go`): a parent's `t.duration` is accumulated *before* the barrier that waits
for its parallel subtests, so it excludes that wait entirely; and `t.Parallel()` resets
`t.start`, so a subtest's reported duration covers only what runs after it is scheduled.

### Reproduction

Two slot hogs plus a parent whose parallel subtest shares its context, run with `-parallel 2`:

```go
func TestParent(t *testing.T) {
	t.Parallel()
	ctx, cancel := context.WithTimeout(t.Context(), 2*time.Second)
	t.Cleanup(cancel)

	t.Run("subtest using parent ctx", func(t *testing.T) {
		t.Parallel()
		if ctx.Err() != nil {
			t.Fatalf("parent ctx expired while this subtest waited for a slot: %v", ctx.Err())
		}
	})
}

func TestHog1(t *testing.T) { t.Parallel(); time.Sleep(8 * time.Second) }
func TestHog2(t *testing.T) { t.Parallel(); time.Sleep(8 * time.Second) }
```

```
probe_test.go:19: subtest resumed: ctx.Err()=context deadline exceeded
--- FAIL: TestParent (0.00s)
    --- FAIL: TestParent/subtest_using_parent_ctx (0.00s)
```

### Suggested fix

- Call `createContext(t)` **inside** each parallel subtest so its deadline starts when the subtest
  actually runs. Any parent-body context shared with `t.Parallel()` subtests carries this bug
  latently; `TestGRPCStatusCode` is the instance that fired here.
- `requireGRPCErrorCode` (`validator_committer_service_test.go:549`) discards the observed error,
  so CI printed only `Should be true`. Including the wanted and actual codes plus the error would
  have made this diagnosable from the log alone, without reproducing it.

Note that this is collateral damage rather than an independent defect: it needs unrelated tests to
hold the parallel slots long enough, which is what #762 caused. Fixing #762 removes this trigger;
fixing the context scoping removes the cascade.

> Investigated and written by an AI agent (Claude Code); please review before acting on it.
